# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'store.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 765)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"border-top-right-radius: 15px;\n"
"border-bottom-left-radius:15px;\n"
"border: 2px solid #999999;\n"
"}\n"
"QPushButton::hover{\n"
"border: 2px solid rgb(85, 255, 255);\n"
"}\n"
"QLabel{\n"
"border-top-right-radius: 15px;\n"
"border-bottom-left-radius:15px;\n"
"border-top-left-radius: 15px;\n"
"border-bottom-right-radius:15px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 40, 991, 691))
        self.stackedWidget.setStyleSheet("#loginwidget{\n"
"background-image:url(./background.png) no-repeat;\n"
"background-position:center;\n"
"background-repeat:no-repeat;\n"
"\n"
"}\n"
"QLabel{\n"
"background-color: rgb(230, 230, 230);\n"
"    font: 14pt \"楷体\";\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginwidget = QtWidgets.QWidget()
        self.loginwidget.setStyleSheet("")
        self.loginwidget.setObjectName("loginwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.title = QtWidgets.QLabel(self.loginwidget)
        self.title.setStyleSheet("background: transparent;\n"
"font: 36pt \"楷体\";\n"
"color: rgb(255, 255, 127);")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.statu = QtWidgets.QWidget(self.loginwidget)
        self.statu.setStyleSheet("background: transparent;")
        self.statu.setObjectName("statu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.statu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.statu)
        self.label_3.setStyleSheet("font: 16pt \"楷体\";\n"
"color: rgb(235, 255, 235);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.username = QtWidgets.QLineEdit(self.statu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        self.username.setStyleSheet("font: 18pt \"楷体\";\n"
"color: rgb(255, 255, 255);")
        self.username.setText("")
        self.username.setObjectName("username")
        self.verticalLayout_2.addWidget(self.username)
        self.label_2 = QtWidgets.QLabel(self.statu)
        self.label_2.setStyleSheet("font: 16pt \"楷体\";\n"
"color: rgb(235, 255, 235);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.password = QtWidgets.QLineEdit(self.statu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        self.password.setStyleSheet("font: 18pt \"楷体\";\n"
"color: rgb(255, 255, 255);")
        self.password.setText("")
        self.password.setObjectName("password")
        self.verticalLayout_2.addWidget(self.password)
        self.login = QtWidgets.QPushButton(self.statu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.login.setAutoFillBackground(False)
        self.login.setStyleSheet("font: 18pt \"楷体\";\n"
"color: rgb(235, 255, 235);")
        self.login.setObjectName("login")
        self.verticalLayout_2.addWidget(self.login)
        self.loginmessage = QtWidgets.QLabel(self.statu)
        self.loginmessage.setStyleSheet("font: 18pt \"楷体\";\n"
"color: rgb(255, 255, 255);")
        self.loginmessage.setAlignment(QtCore.Qt.AlignCenter)
        self.loginmessage.setObjectName("loginmessage")
        self.verticalLayout_2.addWidget(self.loginmessage)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 3)
        self.verticalLayout_2.setStretch(4, 3)
        self.verticalLayout_2.setStretch(5, 2)
        self.horizontalLayout_2.addWidget(self.statu)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(3, 3)
        self.verticalLayout.setStretch(4, 1)
        self.stackedWidget.addWidget(self.loginwidget)
        self.analysiswidget = QtWidgets.QWidget()
        self.analysiswidget.setObjectName("analysiswidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.analysiswidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 609, 991, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_19.addWidget(self.label_29)
        self.buttonprintexecl = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonprintexecl.sizePolicy().hasHeightForWidth())
        self.buttonprintexecl.setSizePolicy(sizePolicy)
        self.buttonprintexecl.setObjectName("buttonprintexecl")
        self.horizontalLayout_19.addWidget(self.buttonprintexecl)
        self.buttonexportexecl = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonexportexecl.sizePolicy().hasHeightForWidth())
        self.buttonexportexecl.setSizePolicy(sizePolicy)
        self.buttonexportexecl.setObjectName("buttonexportexecl")
        self.horizontalLayout_19.addWidget(self.buttonexportexecl)
        self.horizontalLayout_19.setStretch(0, 5)
        self.horizontalLayout_19.setStretch(1, 1)
        self.horizontalLayout_19.setStretch(2, 1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.analysiswidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 991, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_20.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_20.setSpacing(75)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.querySalesInfoButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.querySalesInfoButton.sizePolicy().hasHeightForWidth())
        self.querySalesInfoButton.setSizePolicy(sizePolicy)
        self.querySalesInfoButton.setObjectName("querySalesInfoButton")
        self.horizontalLayout_20.addWidget(self.querySalesInfoButton)
        self.queryCustomerInfoButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryCustomerInfoButton.sizePolicy().hasHeightForWidth())
        self.queryCustomerInfoButton.setSizePolicy(sizePolicy)
        self.queryCustomerInfoButton.setObjectName("queryCustomerInfoButton")
        self.horizontalLayout_20.addWidget(self.queryCustomerInfoButton)
        self.queryWarehouseInfoButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryWarehouseInfoButton.sizePolicy().hasHeightForWidth())
        self.queryWarehouseInfoButton.setSizePolicy(sizePolicy)
        self.queryWarehouseInfoButton.setObjectName("queryWarehouseInfoButton")
        self.horizontalLayout_20.addWidget(self.queryWarehouseInfoButton)
        self.queryGoodsDetailInfoButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryGoodsDetailInfoButton.sizePolicy().hasHeightForWidth())
        self.queryGoodsDetailInfoButton.setSizePolicy(sizePolicy)
        self.queryGoodsDetailInfoButton.setObjectName("queryGoodsDetailInfoButton")
        self.horizontalLayout_20.addWidget(self.queryGoodsDetailInfoButton)
        self.execltableWidget = QtWidgets.QTableWidget(self.analysiswidget)
        self.execltableWidget.setGeometry(QtCore.QRect(30, 150, 961, 451))
        self.execltableWidget.setObjectName("execltableWidget")
        self.execltableWidget.setColumnCount(0)
        self.execltableWidget.setRowCount(0)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.analysiswidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 80, 991, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_21.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_21.setSpacing(75)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.queryTop10BankInfoButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryTop10BankInfoButton.sizePolicy().hasHeightForWidth())
        self.queryTop10BankInfoButton.setSizePolicy(sizePolicy)
        self.queryTop10BankInfoButton.setObjectName("queryTop10BankInfoButton")
        self.horizontalLayout_21.addWidget(self.queryTop10BankInfoButton)
        self.queryTop100GoodsInfopushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryTop100GoodsInfopushButton.sizePolicy().hasHeightForWidth())
        self.queryTop100GoodsInfopushButton.setSizePolicy(sizePolicy)
        self.queryTop100GoodsInfopushButton.setObjectName("queryTop100GoodsInfopushButton")
        self.horizontalLayout_21.addWidget(self.queryTop100GoodsInfopushButton)
        self.queryRemainLessThan10Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryRemainLessThan10Button.sizePolicy().hasHeightForWidth())
        self.queryRemainLessThan10Button.setSizePolicy(sizePolicy)
        self.queryRemainLessThan10Button.setObjectName("queryRemainLessThan10Button")
        self.horizontalLayout_21.addWidget(self.queryRemainLessThan10Button)
        self.querySuggestedPromotionalItemsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.querySuggestedPromotionalItemsButton.sizePolicy().hasHeightForWidth())
        self.querySuggestedPromotionalItemsButton.setSizePolicy(sizePolicy)
        self.querySuggestedPromotionalItemsButton.setObjectName("querySuggestedPromotionalItemsButton")
        self.horizontalLayout_21.addWidget(self.querySuggestedPromotionalItemsButton)
        self.stackedWidget.addWidget(self.analysiswidget)
        self.record_drives_widget = QtWidgets.QWidget()
        self.record_drives_widget.setStyleSheet("")
        self.record_drives_widget.setObjectName("record_drives_widget")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.record_drives_widget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(30, 50, 461, 39))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.drive_uuid = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drive_uuid.sizePolicy().hasHeightForWidth())
        self.drive_uuid.setSizePolicy(sizePolicy)
        self.drive_uuid.setObjectName("drive_uuid")
        self.horizontalLayout_10.addWidget(self.drive_uuid)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 3)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.record_drives_widget)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(30, 200, 461, 39))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.drive_type = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drive_type.sizePolicy().hasHeightForWidth())
        self.drive_type.setSizePolicy(sizePolicy)
        self.drive_type.setObjectName("drive_type")
        self.horizontalLayout_11.addWidget(self.drive_type)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 3)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.record_drives_widget)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(530, 50, 461, 39))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.drive_product = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drive_product.sizePolicy().hasHeightForWidth())
        self.drive_product.setSizePolicy(sizePolicy)
        self.drive_product.setObjectName("drive_product")
        self.horizontalLayout_12.addWidget(self.drive_product)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 3)
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.record_drives_widget)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(530, 100, 461, 39))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.drive_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drive_name.sizePolicy().hasHeightForWidth())
        self.drive_name.setSizePolicy(sizePolicy)
        self.drive_name.setObjectName("drive_name")
        self.horizontalLayout_13.addWidget(self.drive_name)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 3)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.record_drives_widget)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(30, 100, 461, 39))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.emmm = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.emmm.setAlignment(QtCore.Qt.AlignCenter)
        self.emmm.setObjectName("emmm")
        self.horizontalLayout_14.addWidget(self.emmm)
        self.drive_version = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drive_version.sizePolicy().hasHeightForWidth())
        self.drive_version.setSizePolicy(sizePolicy)
        self.drive_version.setObjectName("drive_version")
        self.horizontalLayout_14.addWidget(self.drive_version)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 3)
        self.position = QtWidgets.QLabel(self.record_drives_widget)
        self.position.setGeometry(QtCore.QRect(140, 260, 41, 31))
        self.position.setObjectName("position")
        self.tableWidget = QtWidgets.QTableWidget(self.record_drives_widget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 250, 971, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(94)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(60)
        self.drives_entry = QtWidgets.QPushButton(self.record_drives_widget)
        self.drives_entry.setGeometry(QtCore.QRect(540, 200, 81, 41))
        self.drives_entry.setObjectName("drives_entry")
        self.ware_message = QtWidgets.QLabel(self.record_drives_widget)
        self.ware_message.setGeometry(QtCore.QRect(220, 580, 621, 31))
        self.ware_message.setAlignment(QtCore.Qt.AlignCenter)
        self.ware_message.setObjectName("ware_message")
        self.drives_change = QtWidgets.QPushButton(self.record_drives_widget)
        self.drives_change.setGeometry(QtCore.QRect(650, 200, 81, 41))
        self.drives_change.setObjectName("drives_change")
        self.drives_delete = QtWidgets.QPushButton(self.record_drives_widget)
        self.drives_delete.setGeometry(QtCore.QRect(760, 200, 81, 41))
        self.drives_delete.setObjectName("drives_delete")
        self.drives_query = QtWidgets.QPushButton(self.record_drives_widget)
        self.drives_query.setGeometry(QtCore.QRect(860, 200, 81, 41))
        self.drives_query.setObjectName("drives_query")
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.record_drives_widget)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(30, 150, 461, 39))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.emmm_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.emmm_2.setAlignment(QtCore.Qt.AlignCenter)
        self.emmm_2.setObjectName("emmm_2")
        self.horizontalLayout_25.addWidget(self.emmm_2)
        self.drive_specification = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drive_specification.sizePolicy().hasHeightForWidth())
        self.drive_specification.setSizePolicy(sizePolicy)
        self.drive_specification.setObjectName("drive_specification")
        self.horizontalLayout_25.addWidget(self.drive_specification)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 3)
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.record_drives_widget)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(530, 150, 461, 39))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_26.addWidget(self.label_30)
        self.drive_number = QtWidgets.QLineEdit(self.horizontalLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drive_number.sizePolicy().hasHeightForWidth())
        self.drive_number.setSizePolicy(sizePolicy)
        self.drive_number.setObjectName("drive_number")
        self.horizontalLayout_26.addWidget(self.drive_number)
        self.horizontalLayout_26.setStretch(0, 1)
        self.horizontalLayout_26.setStretch(1, 3)
        self.stackedWidget.addWidget(self.record_drives_widget)
        self.adminwidget = QtWidgets.QWidget()
        self.adminwidget.setObjectName("adminwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.adminwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 931, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.changestoresattributes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changestoresattributes.sizePolicy().hasHeightForWidth())
        self.changestoresattributes.setSizePolicy(sizePolicy)
        self.changestoresattributes.setObjectName("changestoresattributes")
        self.horizontalLayout_15.addWidget(self.changestoresattributes)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.changeprofitbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeprofitbutton.sizePolicy().hasHeightForWidth())
        self.changeprofitbutton.setSizePolicy(sizePolicy)
        self.changeprofitbutton.setObjectName("changeprofitbutton")
        self.horizontalLayout_15.addWidget(self.changeprofitbutton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem9)
        self.customer_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customer_button.sizePolicy().hasHeightForWidth())
        self.customer_button.setSizePolicy(sizePolicy)
        self.customer_button.setObjectName("customer_button")
        self.horizontalLayout_15.addWidget(self.customer_button)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.adminstacked = QtWidgets.QStackedWidget(self.adminwidget)
        self.adminstacked.setGeometry(QtCore.QRect(30, 130, 911, 561))
        self.adminstacked.setStyleSheet("")
        self.adminstacked.setObjectName("adminstacked")
        self.manager_man = QtWidgets.QWidget()
        self.manager_man.setObjectName("manager_man")
        self.layoutWidget_2 = QtWidgets.QWidget(self.manager_man)
        self.layoutWidget_2.setGeometry(QtCore.QRect(230, 0, 561, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.title_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.horizontalLayout_17.addWidget(self.title_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.horizontalLayout_17.setStretch(0, 2)
        self.horizontalLayout_17.setStretch(1, 3)
        self.horizontalLayout_17.setStretch(2, 2)
        self.statu_2 = QtWidgets.QWidget(self.manager_man)
        self.statu_2.setGeometry(QtCore.QRect(20, 60, 461, 461))
        self.statu_2.setObjectName("statu_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.statu_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_21 = QtWidgets.QLabel(self.statu_2)
        self.label_21.setStyleSheet("")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.label_9 = QtWidgets.QLabel(self.statu_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.resigner_name = QtWidgets.QLineEdit(self.statu_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resigner_name.sizePolicy().hasHeightForWidth())
        self.resigner_name.setSizePolicy(sizePolicy)
        self.resigner_name.setText("")
        self.resigner_name.setObjectName("resigner_name")
        self.verticalLayout_3.addWidget(self.resigner_name)
        self.label_13 = QtWidgets.QLabel(self.statu_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.resigner_password_1 = QtWidgets.QLineEdit(self.statu_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resigner_password_1.sizePolicy().hasHeightForWidth())
        self.resigner_password_1.setSizePolicy(sizePolicy)
        self.resigner_password_1.setText("")
        self.resigner_password_1.setObjectName("resigner_password_1")
        self.verticalLayout_3.addWidget(self.resigner_password_1)
        self.label_19 = QtWidgets.QLabel(self.statu_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.resigner_password_2 = QtWidgets.QLineEdit(self.statu_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resigner_password_2.sizePolicy().hasHeightForWidth())
        self.resigner_password_2.setSizePolicy(sizePolicy)
        self.resigner_password_2.setText("")
        self.resigner_password_2.setObjectName("resigner_password_2")
        self.verticalLayout_3.addWidget(self.resigner_password_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_20 = QtWidgets.QLabel(self.statu_2)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_16.addWidget(self.label_20)
        self.resign_type = QtWidgets.QComboBox(self.statu_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resign_type.sizePolicy().hasHeightForWidth())
        self.resign_type.setSizePolicy(sizePolicy)
        self.resign_type.setStyleSheet("border: 0px solid #999999;")
        self.resign_type.setObjectName("resign_type")
        self.resign_type.addItem("")
        self.resign_type.addItem("")
        self.resign_type.addItem("")
        self.horizontalLayout_16.addWidget(self.resign_type)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.horizontalLayout_16.setStretch(0, 2)
        self.horizontalLayout_16.setStretch(1, 2)
        self.horizontalLayout_16.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.admin_registered = QtWidgets.QPushButton(self.statu_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_registered.sizePolicy().hasHeightForWidth())
        self.admin_registered.setSizePolicy(sizePolicy)
        self.admin_registered.setAutoFillBackground(False)
        self.admin_registered.setObjectName("admin_registered")
        self.verticalLayout_3.addWidget(self.admin_registered)
        self.loginmessage_2 = QtWidgets.QLabel(self.statu_2)
        self.loginmessage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.loginmessage_2.setObjectName("loginmessage_2")
        self.verticalLayout_3.addWidget(self.loginmessage_2)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 2)
        self.verticalLayout_3.setStretch(3, 2)
        self.verticalLayout_3.setStretch(4, 2)
        self.verticalLayout_3.setStretch(5, 2)
        self.verticalLayout_3.setStretch(6, 2)
        self.verticalLayout_3.setStretch(7, 2)
        self.verticalLayout_3.setStretch(8, 3)
        self.verticalLayout_3.setStretch(9, 2)
        self.statu_4 = QtWidgets.QWidget(self.manager_man)
        self.statu_4.setGeometry(QtCore.QRect(500, 290, 411, 261))
        self.statu_4.setObjectName("statu_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.statu_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_24 = QtWidgets.QLabel(self.statu_4)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_5.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.statu_4)
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_5.addWidget(self.label_25)
        self.change_username = QtWidgets.QLineEdit(self.statu_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_username.sizePolicy().hasHeightForWidth())
        self.change_username.setSizePolicy(sizePolicy)
        self.change_username.setText("")
        self.change_username.setObjectName("change_username")
        self.verticalLayout_5.addWidget(self.change_username)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_26 = QtWidgets.QLabel(self.statu_4)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_18.addWidget(self.label_26)
        self.change_type = QtWidgets.QComboBox(self.statu_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_type.sizePolicy().hasHeightForWidth())
        self.change_type.setSizePolicy(sizePolicy)
        self.change_type.setObjectName("change_type")
        self.change_type.addItem("")
        self.change_type.addItem("")
        self.change_type.addItem("")
        self.horizontalLayout_18.addWidget(self.change_type)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem14)
        self.horizontalLayout_18.setStretch(0, 2)
        self.horizontalLayout_18.setStretch(1, 2)
        self.horizontalLayout_18.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.admin_change_user = QtWidgets.QPushButton(self.statu_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_change_user.sizePolicy().hasHeightForWidth())
        self.admin_change_user.setSizePolicy(sizePolicy)
        self.admin_change_user.setAutoFillBackground(False)
        self.admin_change_user.setObjectName("admin_change_user")
        self.verticalLayout_5.addWidget(self.admin_change_user)
        self.loginmessage_4 = QtWidgets.QLabel(self.statu_4)
        self.loginmessage_4.setAlignment(QtCore.Qt.AlignCenter)
        self.loginmessage_4.setObjectName("loginmessage_4")
        self.verticalLayout_5.addWidget(self.loginmessage_4)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_5.setStretch(2, 2)
        self.verticalLayout_5.setStretch(3, 3)
        self.verticalLayout_5.setStretch(4, 3)
        self.verticalLayout_5.setStretch(5, 2)
        self.statu_3 = QtWidgets.QWidget(self.manager_man)
        self.statu_3.setGeometry(QtCore.QRect(500, 60, 401, 231))
        self.statu_3.setStyleSheet("")
        self.statu_3.setObjectName("statu_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.statu_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_22 = QtWidgets.QLabel(self.statu_3)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.statu_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.delete_username = QtWidgets.QLineEdit(self.statu_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_username.sizePolicy().hasHeightForWidth())
        self.delete_username.setSizePolicy(sizePolicy)
        self.delete_username.setText("")
        self.delete_username.setObjectName("delete_username")
        self.verticalLayout_4.addWidget(self.delete_username)
        self.admin_delete_user = QtWidgets.QPushButton(self.statu_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_delete_user.sizePolicy().hasHeightForWidth())
        self.admin_delete_user.setSizePolicy(sizePolicy)
        self.admin_delete_user.setAutoFillBackground(False)
        self.admin_delete_user.setStyleSheet("")
        self.admin_delete_user.setObjectName("admin_delete_user")
        self.verticalLayout_4.addWidget(self.admin_delete_user)
        self.loginmessage_3 = QtWidgets.QLabel(self.statu_3)
        self.loginmessage_3.setStyleSheet("\n"
"border-top-right-radius: 15px;\n"
"border-bottom-left-radius:15px;\n"
"border-top-left-radius: 15px;\n"
"border-bottom-right-radius:15px;\n"
"")
        self.loginmessage_3.setAlignment(QtCore.Qt.AlignCenter)
        self.loginmessage_3.setObjectName("loginmessage_3")
        self.verticalLayout_4.addWidget(self.loginmessage_3)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_4.setStretch(2, 2)
        self.verticalLayout_4.setStretch(3, 2)
        self.verticalLayout_4.setStretch(4, 2)
        self.adminstacked.addWidget(self.manager_man)
        self.customer = QtWidgets.QWidget()
        self.customer.setObjectName("customer")
        self.customer_table = QtWidgets.QTableWidget(self.customer)
        self.customer_table.setGeometry(QtCore.QRect(60, 130, 801, 321))
        self.customer_table.setObjectName("customer_table")
        self.customer_table.setColumnCount(4)
        self.customer_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.customer_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.customer_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.customer_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.customer_table.setHorizontalHeaderItem(3, item)
        self.label_27 = QtWidgets.QLabel(self.customer)
        self.label_27.setGeometry(QtCore.QRect(340, 80, 251, 41))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.adminstacked.addWidget(self.customer)
        self.change_log_widget = QtWidgets.QWidget()
        self.change_log_widget.setObjectName("change_log_widget")
        self.log_widget = QtWidgets.QTableWidget(self.change_log_widget)
        self.log_widget.setGeometry(QtCore.QRect(60, 70, 801, 321))
        self.log_widget.setObjectName("log_widget")
        self.log_widget.setColumnCount(7)
        self.log_widget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_widget.setItem(0, 6, item)
        self.admin_change_log = QtWidgets.QPushButton(self.change_log_widget)
        self.admin_change_log.setGeometry(QtCore.QRect(390, 430, 121, 41))
        self.admin_change_log.setObjectName("admin_change_log")
        self.adminstacked.addWidget(self.change_log_widget)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.adminwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 70, 931, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem15)
        self.record_drives = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_drives.sizePolicy().hasHeightForWidth())
        self.record_drives.setSizePolicy(sizePolicy)
        self.record_drives.setObjectName("record_drives")
        self.horizontalLayout_24.addWidget(self.record_drives)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem16)
        self.fix_drives = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fix_drives.sizePolicy().hasHeightForWidth())
        self.fix_drives.setSizePolicy(sizePolicy)
        self.fix_drives.setObjectName("fix_drives")
        self.horizontalLayout_24.addWidget(self.fix_drives)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem17)
        self.change_logs = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_logs.sizePolicy().hasHeightForWidth())
        self.change_logs.setSizePolicy(sizePolicy)
        self.change_logs.setObjectName("change_logs")
        self.horizontalLayout_24.addWidget(self.change_logs)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem18)
        self.admin_manager_user = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.admin_manager_user.sizePolicy().hasHeightForWidth())
        self.admin_manager_user.setSizePolicy(sizePolicy)
        self.admin_manager_user.setObjectName("admin_manager_user")
        self.horizontalLayout_24.addWidget(self.admin_manager_user)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem19)
        self.stackedWidget.addWidget(self.adminwidget)
        self.fixerwidget = QtWidgets.QWidget()
        self.fixerwidget.setObjectName("fixerwidget")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.fixerwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(30, 110, 962, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.fixer_drive_name = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.fixer_drive_name.setObjectName("fixer_drive_name")
        self.horizontalLayout_3.addWidget(self.fixer_drive_name)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.fixer_drive_version = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.fixer_drive_version.setObjectName("fixer_drive_version")
        self.horizontalLayout_4.addWidget(self.fixer_drive_version)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.fixer_drive_id = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.fixer_drive_id.setObjectName("fixer_drive_id")
        self.horizontalLayout_5.addWidget(self.fixer_drive_id)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_31.addWidget(self.label_31)
        self.fixer_drive_spec = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.fixer_drive_spec.setObjectName("fixer_drive_spec")
        self.horizontalLayout_31.addWidget(self.fixer_drive_spec)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_31)
        self.widget = QtWidgets.QWidget(self.fixerwidget)
        self.widget.setGeometry(QtCore.QRect(50, 470, 891, 211))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 70, 751, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_9.addWidget(self.label_28)
        self.fixer_fixing_status = QtWidgets.QComboBox(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixer_fixing_status.sizePolicy().hasHeightForWidth())
        self.fixer_fixing_status.setSizePolicy(sizePolicy)
        self.fixer_fixing_status.setObjectName("fixer_fixing_status")
        self.fixer_fixing_status.addItem("")
        self.fixer_fixing_status.addItem("")
        self.fixer_fixing_status.addItem("")
        self.horizontalLayout_9.addWidget(self.fixer_fixing_status)
        self.fixer_commit = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixer_commit.sizePolicy().hasHeightForWidth())
        self.fixer_commit.setSizePolicy(sizePolicy)
        self.fixer_commit.setObjectName("fixer_commit")
        self.horizontalLayout_9.addWidget(self.fixer_commit)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 3)
        self.horizontalLayout_9.setStretch(2, 2)
        self.fixer_message = QtWidgets.QLabel(self.widget)
        self.fixer_message.setGeometry(QtCore.QRect(240, 140, 393, 33))
        self.fixer_message.setStyleSheet("font: 18pt \"楷体\";\n"
"color: rgb(255, 255, 255);")
        self.fixer_message.setAlignment(QtCore.Qt.AlignCenter)
        self.fixer_message.setObjectName("fixer_message")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(20, 10, 751, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.fixer_search_drives = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixer_search_drives.sizePolicy().hasHeightForWidth())
        self.fixer_search_drives.setSizePolicy(sizePolicy)
        self.fixer_search_drives.setObjectName("fixer_search_drives")
        self.horizontalLayout_7.addWidget(self.fixer_search_drives)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 3)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.fixer_search_drives_and_add = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixer_search_drives_and_add.sizePolicy().hasHeightForWidth())
        self.fixer_search_drives_and_add.setSizePolicy(sizePolicy)
        self.fixer_search_drives_and_add.setStyleSheet("")
        self.fixer_search_drives_and_add.setObjectName("fixer_search_drives_and_add")
        self.horizontalLayout_8.addWidget(self.fixer_search_drives_and_add)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 4)
        self.horizontalLayout_8.setStretch(2, 1)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.fixerwidget)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(30, 190, 921, 61))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_23.addWidget(self.label_14)
        self.fixer_drive_status = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.fixer_drive_status.setObjectName("fixer_drive_status")
        self.horizontalLayout_23.addWidget(self.fixer_drive_status)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_28.addWidget(self.label_8)
        self.fixer_drive_etpye = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.fixer_drive_etpye.setObjectName("fixer_drive_etpye")
        self.horizontalLayout_28.addWidget(self.fixer_drive_etpye)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_30.addWidget(self.label_11)
        self.fixer_drive_department = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.fixer_drive_department.setObjectName("fixer_drive_department")
        self.horizontalLayout_30.addWidget(self.fixer_drive_department)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_30)
        self.cbevvv = QtWidgets.QLabel(self.fixerwidget)
        self.cbevvv.setGeometry(QtCore.QRect(30, 330, 223, 57))
        self.cbevvv.setAlignment(QtCore.Qt.AlignCenter)
        self.cbevvv.setObjectName("cbevvv")
        self.fixer_drive_ereason = QtWidgets.QTextBrowser(self.fixerwidget)
        self.fixer_drive_ereason.setGeometry(QtCore.QRect(270, 280, 591, 151))
        self.fixer_drive_ereason.setObjectName("fixer_drive_ereason")
        self.stackedWidget.addWidget(self.fixerwidget)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 991, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.welcomeUser = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.welcomeUser.setStyleSheet("font: 20pt \"楷体\";\n"
"")
        self.welcomeUser.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeUser.setObjectName("welcomeUser")
        self.horizontalLayout_22.addWidget(self.welcomeUser)
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setGeometry(QtCore.QRect(960, 740, 24, 24))
        self.logoutButton.setStyleSheet("\n"
"background-color:rgb(255, 255, 255);\n"
"border-top-right-radius: 12px;\n"
"border-bottom-left-radius:12px;\n"
"border-top-left-radius: 12px;\n"
"border-bottom-right-radius:12px;\n"
"border: 2px solid #999999;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.logoutButton.setObjectName("logoutButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.adminstacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "设备管理系统"))
        self.label_3.setText(_translate("MainWindow", "Username:"))
        self.username.setPlaceholderText(_translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.password.setPlaceholderText(_translate("MainWindow", "Input"))
        self.login.setText(_translate("MainWindow", "Log in"))
        self.loginmessage.setText(_translate("MainWindow", "Password Error"))
        self.label_29.setText(_translate("MainWindow", "导出成功"))
        self.buttonprintexecl.setText(_translate("MainWindow", "打印"))
        self.buttonexportexecl.setText(_translate("MainWindow", "导出"))
        self.querySalesInfoButton.setText(_translate("MainWindow", "故障设备"))
        self.queryCustomerInfoButton.setText(_translate("MainWindow", "未修设备"))
        self.queryWarehouseInfoButton.setText(_translate("MainWindow", "在修设备"))
        self.queryGoodsDetailInfoButton.setText(_translate("MainWindow", "所有商品详细情况"))
        self.queryTop10BankInfoButton.setText(_translate("MainWindow", "销售 利润 前10品牌"))
        self.queryTop100GoodsInfopushButton.setText(_translate("MainWindow", "销售 数量 前100商品"))
        self.queryRemainLessThan10Button.setText(_translate("MainWindow", "余量警报"))
        self.querySuggestedPromotionalItemsButton.setText(_translate("MainWindow", "建议促销商品"))
        self.label_15.setText(_translate("MainWindow", "编号"))
        self.label_16.setText(_translate("MainWindow", "类型"))
        self.label_17.setText(_translate("MainWindow", "制造单位"))
        self.label_18.setText(_translate("MainWindow", "设备名称"))
        self.emmm.setText(_translate("MainWindow", "型号"))
        self.position.setText(_translate("MainWindow", "定位"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "类型"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "状态"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "版本"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "规格"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "生产商"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "部门"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "损坏类型"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "损坏原因"))
        self.drives_entry.setText(_translate("MainWindow", "添加"))
        self.ware_message.setText(_translate("MainWindow", "message"))
        self.drives_change.setText(_translate("MainWindow", "修改"))
        self.drives_delete.setText(_translate("MainWindow", "删除"))
        self.drives_query.setText(_translate("MainWindow", "查询"))
        self.emmm_2.setText(_translate("MainWindow", "规格"))
        self.label_30.setText(_translate("MainWindow", "进货数"))
        self.changestoresattributes.setText(_translate("MainWindow", "修改商品数量、单价"))
        self.changeprofitbutton.setText(_translate("MainWindow", "修改商品剩余数量、利润"))
        self.customer_button.setText(_translate("MainWindow", "查看客户信息"))
        self.title_2.setText(_translate("MainWindow", "人员账号管理"))
        self.label_21.setText(_translate("MainWindow", "注册"))
        self.label_9.setText(_translate("MainWindow", "Username:"))
        self.resigner_name.setPlaceholderText(_translate("MainWindow", "Input"))
        self.label_13.setText(_translate("MainWindow", "Password:"))
        self.resigner_password_1.setPlaceholderText(_translate("MainWindow", "Input"))
        self.label_19.setText(_translate("MainWindow", "Password Again:"))
        self.resigner_password_2.setPlaceholderText(_translate("MainWindow", "Input"))
        self.label_20.setText(_translate("MainWindow", "职位"))
        self.resign_type.setItemText(0, _translate("MainWindow", "staff"))
        self.resign_type.setItemText(1, _translate("MainWindow", "fixer"))
        self.resign_type.setItemText(2, _translate("MainWindow", "admin"))
        self.admin_registered.setText(_translate("MainWindow", "注册"))
        self.loginmessage_2.setText(_translate("MainWindow", "错误"))
        self.label_24.setText(_translate("MainWindow", "修改职位"))
        self.label_25.setText(_translate("MainWindow", "Username:"))
        self.change_username.setPlaceholderText(_translate("MainWindow", "Input"))
        self.label_26.setText(_translate("MainWindow", "职位"))
        self.change_type.setItemText(0, _translate("MainWindow", "staff"))
        self.change_type.setItemText(1, _translate("MainWindow", "fixer"))
        self.change_type.setItemText(2, _translate("MainWindow", "admin"))
        self.admin_change_user.setText(_translate("MainWindow", "修改"))
        self.loginmessage_4.setText(_translate("MainWindow", "错误"))
        self.label_22.setText(_translate("MainWindow", "删除人员"))
        self.label_23.setText(_translate("MainWindow", "Username:"))
        self.delete_username.setPlaceholderText(_translate("MainWindow", "Input"))
        self.admin_delete_user.setText(_translate("MainWindow", "删除"))
        self.loginmessage_3.setText(_translate("MainWindow", "错误"))
        item = self.customer_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID编号"))
        item = self.customer_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "客户名"))
        item = self.customer_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "积分"))
        item = self.customer_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "上次购买时间"))
        self.label_27.setText(_translate("MainWindow", "客户信息"))
        item = self.log_widget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.log_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "日志ID"))
        item = self.log_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "日志记录"))
        item = self.log_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "操作用户ID"))
        item = self.log_widget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "用户名"))
        item = self.log_widget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "设备名"))
        item = self.log_widget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "设备ID"))
        item = self.log_widget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "版本"))
        __sortingEnabled = self.log_widget.isSortingEnabled()
        self.log_widget.setSortingEnabled(False)
        item = self.log_widget.item(0, 0)
        item.setText(_translate("MainWindow", "a"))
        item = self.log_widget.item(0, 1)
        item.setText(_translate("MainWindow", "b"))
        item = self.log_widget.item(0, 2)
        item.setText(_translate("MainWindow", "c"))
        item = self.log_widget.item(0, 3)
        item.setText(_translate("MainWindow", "d"))
        item = self.log_widget.item(0, 4)
        item.setText(_translate("MainWindow", "e"))
        item = self.log_widget.item(0, 5)
        item.setText(_translate("MainWindow", "f"))
        item = self.log_widget.item(0, 6)
        item.setText(_translate("MainWindow", "g"))
        self.log_widget.setSortingEnabled(__sortingEnabled)
        self.admin_change_log.setText(_translate("MainWindow", "修改"))
        self.record_drives.setText(_translate("MainWindow", "设备录入"))
        self.fix_drives.setText(_translate("MainWindow", "设备维修"))
        self.change_logs.setText(_translate("MainWindow", "更改日志"))
        self.admin_manager_user.setText(_translate("MainWindow", "员工账号管理"))
        self.label.setText(_translate("MainWindow", "设备名称"))
        self.fixer_drive_name.setText(_translate("MainWindow", "fixer_drive_name"))
        self.label_4.setText(_translate("MainWindow", "设备型号"))
        self.fixer_drive_version.setText(_translate("MainWindow", "fixer_drive_version"))
        self.label_5.setText(_translate("MainWindow", "设备ID"))
        self.fixer_drive_id.setText(_translate("MainWindow", "fixer_drive_id"))
        self.label_31.setText(_translate("MainWindow", "规格"))
        self.fixer_drive_spec.setText(_translate("MainWindow", "fixer_drive_spec"))
        self.label_28.setText(_translate("MainWindow", "维修情况"))
        self.fixer_fixing_status.setItemText(0, _translate("MainWindow", "Error"))
        self.fixer_fixing_status.setItemText(1, _translate("MainWindow", "Normal"))
        self.fixer_fixing_status.setItemText(2, _translate("MainWindow", "Fixing"))
        self.fixer_commit.setText(_translate("MainWindow", "提交"))
        self.fixer_message.setText(_translate("MainWindow", "message"))
        self.label_7.setText(_translate("MainWindow", "搜索设备"))
        self.label_6.setText(_translate("MainWindow", "设备ID"))
        self.fixer_search_drives_and_add.setText(_translate("MainWindow", "添加"))
        self.label_14.setText(_translate("MainWindow", "当前状态"))
        self.fixer_drive_status.setText(_translate("MainWindow", "fixer_drive_status"))
        self.label_8.setText(_translate("MainWindow", "损坏类型"))
        self.fixer_drive_etpye.setText(_translate("MainWindow", "fixer_drive_etpye"))
        self.label_11.setText(_translate("MainWindow", "设备所属部门"))
        self.fixer_drive_department.setText(_translate("MainWindow", "fixer_drive_department"))
        self.cbevvv.setText(_translate("MainWindow", "损坏原因"))
        self.fixer_drive_ereason.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">fixer_drive_ereason</p></body></html>"))
        self.welcomeUser.setText(_translate("MainWindow", "欢迎您：请登录"))
        self.logoutButton.setText(_translate("MainWindow", "O"))

